camera_mode: track
char_file: C:\Users\linus\Desktop\codesign\codesign\test_native_amp\g1_modified.xml
contact_bodies:
- left_knee_link
- left_ankle_pitch_link
- left_ankle_roll_link
- right_knee_link
- right_ankle_pitch_link
- right_ankle_roll_link
enable_early_termination: true
enable_phase_obs: false
enable_tar_obs: false
env_name: amp
episode_length: 10.0
global_obs: true
init_pose:
- 0
- 0
- 0.8
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 1.57
- 0
- 0
- 0
- 0
- 0
- 0
- 1.57
- 0
- 0
- 0
key_bodies:
- left_ankle_roll_link
- right_ankle_roll_link
- head_link
- left_wrist_yaw_link
- right_wrist_yaw_link
motion_file: C:\Users\linus\Desktop\codesign\MimicKit\data/motions/g1/g1_walk.pkl
num_disc_obs_steps: 10
pose_termination: false
rand_reset: true
ref_char_offset:
- 2.0
- 0.0
- 0.0
reward_key_pos_scale: 10.0
reward_key_pos_w: 0.15
reward_pose_scale: 0.25
reward_pose_w: 0.5
reward_root_pose_scale: 5.0
reward_root_pose_w: 0.15
reward_root_vel_scale: 1.0
reward_root_vel_w: 0.1
reward_vel_scale: 0.01
reward_vel_w: 0.1
root_height_obs: true
zero_center_action: true
