name: codesign
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - cmake
  - ninja
  - gxx_linux-64
  - xorg-libxrandr
  - xorg-libxinerama
  - xorg-libxcursor
  - xorg-libxi
  - xorg-libxext
  - xorg-libx11
  - libgl-devel
  - libegl-devel
  - libglu

  - pip:
      - absl-py==2.3.1
      - alphashape==1.3.1
      - annotated-types==0.7.0
      - cbor2==5.8.0
      - certifi
      - charset-normalizer==3.4.4
      - click==8.3.1
      - click-log==0.4.0
      - cloudpickle==3.1.2
      - coacd==1.0.7
      - colorama==0.4.6
      - contourpy==1.3.2
      - coverage==7.13.1
      - cycler==0.12.1
      - etils==1.13.0
      - farama-notifications==0.0.4
      - fast-simplification==0.1.13
      - filelock
      - fonttools==4.61.1
      - fsspec
      - gitdb==4.0.12
      - gitpython==3.1.46
      - glfw==2.10.0
      - gymnasium==1.2.3
      - idna==3.11
      - imgui-bundle==1.92.5
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - mujoco>=3.0.0
      - mujoco-warp==0.0.2
      - networkx==3.4.2
      - numpy>=2.0.0
      - packaging
      - pillow
      - platformdirs
      - protobuf
      - pycollada==0.9.2
      - pydantic>=2.0.0
      - pydantic-core
      - pyglet==2.1.12
      - pyopengl==3.1.10
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - requests==2.32.5
      - rtree==1.4.1
      - scipy>=1.10.0
      - sentry-sdk
      - shapely>=2.0.0
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.13.1
      - tensorboardx==2.6.4
      - tomli
      - torch>=2.0.0
      - torchaudio
      - torchvision
      - tqdm==4.67.1
      - trimesh==4.11.1
      - typing-extensions
      - typing-inspection
      - urllib3
      - usd-core
      - wandb
      - warp-lang
